// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bGh2YvDkTUYjw9gOAQdl7jyuF4R-YYA',
    appId: '1:70578591346:web:1b3b65043df5cdb6eb54eb',
    messagingSenderId: '70578591346',
    projectId: 'gestion-cours-tpf',
    authDomain: 'gestion-cours-tpf.firebaseapp.com',
    storageBucket: 'gestion-cours-tpf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSaZBLeEQOn0HqF__WRrubLx1165CrB5k',
    appId: '1:70578591346:android:5a72eee28cd6f7c0eb54eb',
    messagingSenderId: '70578591346',
    projectId: 'gestion-cours-tpf',
    storageBucket: 'gestion-cours-tpf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9gm7ZHQO4pZimqh3zTDYXom2Atup_rs',
    appId: '1:70578591346:ios:6fe4037bdd6a2628eb54eb',
    messagingSenderId: '70578591346',
    projectId: 'gestion-cours-tpf',
    storageBucket: 'gestion-cours-tpf.appspot.com',
    iosBundleId: 'com.example.tpFinalFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9gm7ZHQO4pZimqh3zTDYXom2Atup_rs',
    appId: '1:70578591346:ios:6fe4037bdd6a2628eb54eb',
    messagingSenderId: '70578591346',
    projectId: 'gestion-cours-tpf',
    storageBucket: 'gestion-cours-tpf.appspot.com',
    iosBundleId: 'com.example.tpFinalFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3bGh2YvDkTUYjw9gOAQdl7jyuF4R-YYA',
    appId: '1:70578591346:web:6f56ace3bc5f9efdeb54eb',
    messagingSenderId: '70578591346',
    projectId: 'gestion-cours-tpf',
    authDomain: 'gestion-cours-tpf.firebaseapp.com',
    storageBucket: 'gestion-cours-tpf.appspot.com',
  );
}
